In [2]:
import pandas as pd
import numpy as np
import sklearn

In [3]:
URL = 'https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv'
df = pd.read_csv(URL)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

In [5]:
housing = train_set.drop("median_house_value", axis=1)
housing_labels = train_set["median_house_value"].copy()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [7]:
median = housing['total_bedrooms'].median()
housing["total_bedrooms"].fillna(value=median)

14196     627.0
8267      787.0
17445     331.0
14265     367.0
2271      431.0
          ...  
11284     201.0
11964     570.0
5390      569.0
860       597.0
15795    1315.0
Name: total_bedrooms, Length: 16512, dtype: float64

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')

In [9]:
housing['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     7341
INLAND        5227
NEAR OCEAN    2086
NEAR BAY      1854
ISLAND           4
Name: count, dtype: int64

In [22]:
mod_housing = housing.replace(
    {
        "<1H OCEAN":"0",
        "INLAND":"1",
        "NEAR OCEAN":"2",
        "NEAR BAY":"3",
        "ISLAND":"4",
    }
)

mod_housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income ocean_proximity  
14196      2300.0       623.0         3.2596               2  
8267       1314.0       756.0         3.8125               2  
17445       915.0       336.0         4.1563               2  
14265      1418.0       355.0         1.9425               2  
2271        874.0       380.0         3.5542               1  
...           ...         ...            ...             ...  
11284       658.0       217.0         6.3700               0  
11964      1753.0       449.0         3.0500               1  
5390       1756.0       527.0         2.9344               0  
860        1777.0       559.0         5.7192               0  
15795      2619.0      1242.0         2.5755               3  

[16512 rows x 9 columns]

In [11]:
housing_wop = housing.drop("ocean_proximity", axis=1)
housing_wop

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542  
...           ...         ...            ...  
11284       658.0       217.0         6.3700  
11964      1753.0       449.0         3.0500  
5390       1756.0       527.0         2.9344  
860        1777.0       559.0         5.7192  
15795      2619.0      1242.0         2.5755  

[16512 rows x 8 columns]

In [12]:
imputer.fit(housing_wop)

SimpleImputer(strategy='median')

In [13]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2129.    ,  437.    , 1167.    ,
        410.    ,    3.5458])

In [14]:
X = imputer.transform(housing_wop)
X

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

In [15]:
y = imputer.fit_transform(housing_wop)
y

array([[-1.1703e+02,  3.2710e+01,  3.3000e+01, ...,  2.3000e+03,
         6.2300e+02,  3.2596e+00],
       [-1.1816e+02,  3.3770e+01,  4.9000e+01, ...,  1.3140e+03,
         7.5600e+02,  3.8125e+00],
       [-1.2048e+02,  3.4660e+01,  4.0000e+00, ...,  9.1500e+02,
         3.3600e+02,  4.1563e+00],
       ...,
       [-1.1838e+02,  3.4030e+01,  3.6000e+01, ...,  1.7560e+03,
         5.2700e+02,  2.9344e+00],
       [-1.2196e+02,  3.7580e+01,  1.5000e+01, ...,  1.7770e+03,
         5.5900e+02,  5.7192e+00],
       [-1.2242e+02,  3.7770e+01,  5.2000e+01, ...,  2.6190e+03,
         1.2420e+03,  2.5755e+00]])

In [16]:
housing_it = pd.DataFrame(X, columns=housing_wop.columns, index=housing_wop.index)
housing_it

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196    -117.03     32.71                33.0       3126.0           627.0   
8267     -118.16     33.77                49.0       3382.0           787.0   
17445    -120.48     34.66                 4.0       1897.0           331.0   
14265    -117.11     32.69                36.0       1421.0           367.0   
2271     -119.80     36.78                43.0       2382.0           431.0   
...          ...       ...                 ...          ...             ...   
11284    -117.96     33.78                35.0       1330.0           201.0   
11964    -117.43     34.02                33.0       3084.0           570.0   
5390     -118.38     34.03                36.0       2101.0           569.0   
860      -121.96     37.58                15.0       3575.0           597.0   
15795    -122.42     37.77                52.0       4226.0          1315.0   

       population  households  median_income  
14196      2300.0       623.0         3.2596  
8267       1314.0       756.0         3.8125  
17445       915.0       336.0         4.1563  
14265      1418.0       355.0         1.9425  
2271        874.0       380.0         3.5542  
...           ...         ...            ...  
11284       658.0       217.0         6.3700  
11964      1753.0       449.0         3.0500  
5390       1756.0       527.0         2.9344  
860        1777.0       559.0         5.7192  
15795      2619.0      1242.0         2.5755  

[16512 rows x 8 columns]

In [17]:
housing_it.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [19]:
housing_cat = housing[['ocean_proximity']]
housing_cat

ocean_proximity
14196      NEAR OCEAN
8267       NEAR OCEAN
17445      NEAR OCEAN
14265      NEAR OCEAN
2271           INLAND
...               ...
11284       <1H OCEAN
11964          INLAND
5390        <1H OCEAN
860         <1H OCEAN
15795        NEAR BAY

[16512 rows x 1 columns]

In [23]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

ordinal_encoder = OrdinalEncoder()

housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded

array([[4.],
       [4.],
       [4.],
       ...,
       [0.],
       [0.],
       [3.]])

In [27]:
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [31]:
housing_onehot = pd.get_dummies(housing['ocean_proximity'])
housing_onehot.head(20)

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
14196      False   False   False     False        True
8267       False   False   False     False        True
17445      False   False   False     False        True
14265      False   False   False     False        True
2271       False    True   False     False       False
17848       True   False   False     False       False
6252        True   False   False     False       False
9389       False   False   False      True       False
6113        True   False   False     False       False
6061        True   False   False     False       False
16030      False   False   False      True       False
8364        True   False   False     False       False
9448       False    True   False     False       False
17529       True   False   False     False       False
5865        True   False   False     False       False
7615        True   False   False     False       False
9707        True   False   False     False       False
16332      False    True   False     False       False
3449        True   False   False     False       False
5199        True   False   False     False       False

In [41]:
from sklearn.base import BaseEstimator, TransformerMixin

# here is the indexes of culemns that we need
rooms_IX, bedrooms_IX, population_IX, household_IX = 3, 4, 5, 6

class CombinerAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_rooms=True):
        self.add_bedrooms_per_rooms = add_bedrooms_per_rooms
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        rooms_per_household = X[:, rooms_IX] / X[:, households_IX]
        population_per_household = X[:, population_IX] / X[:, household_IX]
        if self.add_bedrooms_per_rooms:
            bedrooms_per_room = X[:, bedrooms_IX] / X[:, rooms_IX]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [42]:
attr_adder = CombinerAttributesAdder()
housing_extra_attribs = attr_adder.transform(housing.values)

In [43]:
housing.values[0, :]


array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN'], dtype=object)

In [44]:
housing_extra_attribs[0,:]

array([-117.03, 32.71, 33.0, 3126.0, 627.0, 2300.0, 623.0, 3.2596,
       'NEAR OCEAN', 5.017656500802568, 3.691813804173355,
       0.20057581573896352], dtype=object)