In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.save('data', arr)

In [8]:
uploaded_arr = np.load("data.npy")
uploaded_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.arange(20)

In [10]:
np.savez('arrays', a=arr, b=arr1)

In [12]:
arrays = np.load('arrays.npz')
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.savez_compressed('array_comp', a=arr, b=arr1)

In [18]:
arrays1 = np.load('array_comp.npz')

In [20]:
arrays1['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])