In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#@title Universal functions - [sqrt] [square] [exp] [log] [modf] [sign] [isnan]


In [5]:
#@title sqrt - roots of numbers
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
#@title square - square of numbers in array
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
#@title exp - exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
#@title log - logorithms
np.log(arr)

<ipython-input-8-786a499cbd98>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [18]:
#@title modf - modifier = 3.2=> 3 & 2
arr1 = np.random.rand(6)
arr1

array([0.7505905 , 0.14588828, 0.73271491, 0.12629382, 0.07473251,
       0.26576468])

In [20]:
array, arra = np.modf(arr1)
print(array)
print(arra)

[0.7505905  0.14588828 0.73271491 0.12629382 0.07473251 0.26576468]
[0. 0. 0. 0. 0. 0.]


In [23]:
#@title sign
arr2 = np.array([-1.35, 345, -634, 5, -7, 6, 6,-7])
print(arr2)
print(np.sign(arr2))

[  -1.35  345.   -634.      5.     -7.      6.      6.     -7.  ]
[-1.  1. -1.  1. -1.  1.  1. -1.]


In [27]:
#@title isnan - is there any nan values
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False])

In [28]:
arr1[0] = np.NaN
arr1

array([       nan, 0.14588828, 0.73271491, 0.12629382, 0.07473251,
       0.26576468])

In [30]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

In [31]:
#@title add, multiply, maximum
arr3 = np.random.rand(6)
arr4 = np.random.rand(6)

In [32]:
arr3

array([0.38997935, 0.61972788, 0.05630473, 0.6712791 , 0.01707125,
       0.96180054])

In [33]:
arr4

array([0.28559178, 0.12217892, 0.15120143, 0.75219453, 0.75515516,
       0.32064282])

In [34]:
np.add(arr3, arr4)

array([0.67557112, 0.7419068 , 0.20750616, 1.42347364, 0.77222641,
       1.28244335])

In [35]:
np.multiply(arr3, arr4)

array([0.11137489, 0.07571768, 0.00851336, 0.50493247, 0.01289144,
       0.30839443])

In [36]:
np.maximum(arr3, arr4)

array([0.38997935, 0.61972788, 0.15120143, 0.75219453, 0.75515516,
       0.96180054])