In [2]:
import numpy as np

In [6]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:

y = np.array([[5., 5., 5.], [4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [9]:
y+x

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [10]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [11]:
y*5

array([[25., 25., 25.],
       [20., 20., 20.]])

In [12]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [17]:
y = y.reshape(3, 2)

In [18]:
y.dot(x)

array([[25., 35., 45.],
       [21., 30., 39.],
       [20., 28., 36.]])

In [20]:
x.dot(y)

array([[27., 25.],
       [69., 64.]])

In [21]:
np.dot(y, x)

array([[25., 35., 45.],
       [21., 30., 39.],
       [20., 28., 36.]])

In [22]:
#@title Linear Algebra
from numpy.linalg import inv