In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
cond = np.array([True, False, True, True, False])

In [4]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.rand(4, 4)
arr

array([[8.17068553e-02, 1.53767800e-01, 5.12544694e-01, 1.92041705e-01],
       [8.76886429e-01, 6.65680838e-01, 1.85303632e-01, 6.33485993e-01],
       [5.90768019e-01, 2.89088854e-04, 4.42585297e-02, 1.07846999e-01],
       [4.92708437e-01, 2.81599021e-01, 3.70541552e-01, 3.37893139e-01]])

In [10]:
results = np.where(arr>3.37893139e-01, True, False)
results

array([[False, False,  True, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False]])