In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5, 4)
arr

array([[0.24576566, 0.76605721, 0.77839159, 0.22864679],
       [0.60494033, 0.68177897, 0.7436756 , 0.14538873],
       [0.23114608, 0.20278559, 0.50766466, 0.82732417],
       [0.64732653, 0.40746664, 0.95075389, 0.99683527],
       [0.96775078, 0.99152117, 0.81609471, 0.66220221]])

In [ ]:
#@title sum
print(arr.sum(), "--1")
# or
print(np.sum(arr)," --2")


In [5]:
arr.sum(axis=1)

array([2.01886126, 2.17578363, 1.7689205 , 3.00238233, 3.43756887])

In [6]:
arr.sum(axis=0)

array([2.69692939, 3.04960958, 3.79658046, 2.86039716])

In [8]:
#@title mean
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr1.mean(axis=0) # 0 + 1 + 2 + 3 + 4 + 5 = 10 / 5 = 2

2.0

In [13]:
#@title cumsum
arr1.cumsum(axis=0)

array([ 0,  1,  3,  6, 10])

In [14]:
arr1

array([0, 1, 2, 3, 4])

In [15]:
np.cumsum(arr1, axis=0)

array([ 0,  1,  3,  6, 10])