In [1]:
import numpy as np

In [2]:
names = np.array(["John", "Jane", "Bob", "Alice", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Isaac", "Julia", "Keith"])
names

array(['John', 'Jane', 'Bob', 'Alice', 'Charlie', 'Diana', 'Ethan',
       'Fiona', 'George', 'Hannah', 'Isaac', 'Julia', 'Keith'],
      dtype='<U7')

In [4]:
data = np.random.rand(13, 4)
data

array([[0.56050318, 0.67120035, 0.37829221, 0.12597484],
       [0.06355591, 0.68549974, 0.7130622 , 0.32947376],
       [0.54056303, 0.39051424, 0.81524492, 0.18026482],
       [0.0350516 , 0.8488456 , 0.99283397, 0.99594258],
       [0.14765104, 0.22610163, 0.42870792, 0.83414097],
       [0.38718806, 0.05418016, 0.11123449, 0.3229616 ],
       [0.39635706, 0.08952574, 0.38211784, 0.2696847 ],
       [0.08969279, 0.53068341, 0.2879954 , 0.4367846 ],
       [0.04227771, 0.17424787, 0.94720671, 0.94814345],
       [0.62861262, 0.25945779, 0.45930712, 0.58550535],
       [0.05309753, 0.7199081 , 0.6227175 , 0.3937397 ],
       [0.23708861, 0.61618205, 0.24813627, 0.94268652],
       [0.87217742, 0.67594977, 0.84443695, 0.44071399]])

In [6]:
#@title Boolean
names == "John"

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [7]:
John_info = data[names == 'John'].copy()
John_info

array([[0.56050318, 0.67120035, 0.37829221, 0.12597484]])

In [13]:
data[names == 'John', 2:]

array([[0.37829221, 0.12597484]])

In [29]:
data[names == ["John" "Jane"]] # Usefull !!!!!!! emas

array([], shape=(0, 4), dtype=float64)

In [28]:
data[names == "John"]

array([[0.56050318, 0.67120035, 0.37829221, 0.12597484]])

In [25]:
data[names == "Jane"]

array([[0.06355591, 0.68549974, 0.7130622 , 0.32947376]])

In [33]:
mask = (names == "John") | (names == "Jane")
mask

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False])

In [34]:
data[mask]

array([[0.56050318, 0.67120035, 0.37829221, 0.12597484],
       [0.06355591, 0.68549974, 0.7130622 , 0.32947376]])

In [35]:
data[(names == "John") | (names == "Jane")]

array([[0.56050318, 0.67120035, 0.37829221, 0.12597484],
       [0.06355591, 0.68549974, 0.7130622 , 0.32947376]])