In [ ]:
import numpy as np

In [ ]:
data1 = [3.5, 5, 4, 6, 76,54,54,4,6] # list
arr1 = np.array(data1) # array1

In [ ]:
data1

[3.5, 5, 4, 6, 76, 54, 54, 4, 6]

In [ ]:
arr1

array([ 3.5,  5. ,  4. ,  6. , 76. , 54. , 54. ,  4. ,  6. ])

In [ ]:
data2 = tuple(range(16))
arr2 = np.array(data2)
print(f"Data:{data2}")
print(f"Array{arr2}")

Data:(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Array[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
arr1.ndim

1

In [8]:
data3 = ([4,3,5,6,4,3], [3,4,4,5,5,4,3,3,4])
arr3 = np.array(data3)
print(f"Data:{data3}")
print(f"Array{arr3}")

Data:([4, 3, 5, 6, 4, 3], [3, 4, 4, 5, 5, 4, 3, 3, 4])
Array[list([4, 3, 5, 6, 4, 3]) list([3, 4, 4, 5, 5, 4, 3, 3, 4])]


<ipython-input-8-086428bad9f8>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array(data3)


In [9]:
arr3.ndim

1

In [11]:
data4 = [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15]] # Nested list
arr4 = np.array(data4)
print(f"Data:{data4}")
print(f"Array:{arr4}")
print(f"Ndim:{arr4.ndim}")

Data:[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]
Array:[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9, 10, 11, 12, 13, 14, 15])]
Ndim:1


<ipython-input-11-96823dfcc6a6>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(data4)


In [12]:
data5 = [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15]] # Nested list
arr5 = np.array(data5)


<ipython-input-12-8bb9c68b60be>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr5 = np.array(data5)


In [13]:
arr5


array([list([1, 2, 3, 4, 5, 6, 7]), list([8, 9, 10, 11, 12, 13, 14, 15])],
      dtype=object)

In [14]:
arr5.ndim

1

In [20]:
data6 = [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15]] # Nested list
arr6 = np.array(data6)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [19]:
arr6.ndim


1

In [40]:
arr7 = np.array([[[1,2,3,4,5,6,7] [[1,2,3,4,5,6,7], [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15], [[1,2,3,4,5,6,7], [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15]]]]]]])
arr7.ndim

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-40-a1e12080573c>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr7 = np.array([[[1,2,3,4,5,6,7] [[1,2,3,4,5,6,7], [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15], [[1,2,3,4,5,6,7], [[1,2,3,4,5,6,7], [8,9,10,11,12,13,14,15]]]]]]])


TypeError: list indices must be integers or slices, not tuple

In [35]:
arr7

array([list([1, 2, 3, 4, 5, 6, 7]), list([8, 9, 10, 11, 12, 13, 14, 15]),
       list([[1, 2, 3, 4, 5, 6, 7], [[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [[1, 2, 3, 4, 5, 6, 7], [[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]]]])],
      dtype=object)

In [41]:
arr7.shape

(3,)

In [42]:
arr7 = np.ones(shape=(4,7))

In [43]:
arr7

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [44]:
arr7.shape


(4, 7)

In [45]:
arr7.ndim

2

In [54]:
data8 = [
    [
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
    ],
    [
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
    ],
    [
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
        [[
        [5,6,7],
        [6,7,8],
        [6,7,8],
    ],],
    ],
]
arr8 = np.array(data8, dtype=object)
arr8.shape
arr8.ndim

5

In [51]:
arr9 = np.arange(21)
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])