In [4]:
import numpy as np

In [14]:
#@title sorting
arr = np.random.rand(4)
arr

array([0.69923404, 0.41999317, 0.65025051, 0.83505752])

In [15]:
sorted_arr = np.sort(arr)

In [16]:
sorted_arr

array([0.41999317, 0.65025051, 0.69923404, 0.83505752])

In [17]:
arr

array([0.69923404, 0.41999317, 0.65025051, 0.83505752])

In [19]:
reverced_arr = -np.sort(-arr)
reverced_arr

array([0.83505752, 0.69923404, 0.65025051, 0.41999317])

In [20]:
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.22632312, -0.02286372,  0.43537323,  0.50014137],
       [ 0.42206362,  0.74834509,  2.20805539,  0.79124556]])

In [22]:
row_str = np.sort(arr2d, axis=0)
row_str

array([[-0.02286372,  0.22632312,  0.43537323,  0.50014137],
       [ 0.42206362,  0.74834509,  0.79124556,  2.20805539]])

In [23]:
col_str = np.sort(arr2d, axis=1)
col_str

array([[-0.02286372,  0.22632312,  0.43537323,  0.50014137],
       [ 0.42206362,  0.74834509,  0.79124556,  2.20805539]])