In [1]:
import numpy as np

In [2]:
#@title Reshape method
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [3]:
arr1 = arr1.reshape(3, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
arr1.T

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
#@title Swapping axes
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
arr1.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [8]:
arr1.swapaxes(0, 1)

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
arr1.swapaxes()

TypeError: swapaxes() takes exactly 2 arguments (0 given)