In [ ]:
import numpy as np # Let's learn about indexing and slicing

In [ ]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[0]

10

In [ ]:
print("  |[index] | array value")
for i in range(9):
  print(f"Array{[i]} = {arr[i]}")

  |[index] | array value
Array[0] = 10
Array[1] = 20
Array[2] = 30
Array[3] = 40
Array[4] = 50
Array[5] = 60
Array[6] = 70
Array[7] = 80
Array[8] = 90


In [ ]:
print("  |[index] | array value")
for i in range(1 , 10): # I add "-" char to index. In this situation taking array values will be reversed
  print(f"Array{[-i]} = {arr[-i]}")

  |[index] | array value
Array[-1] = 90
Array[-2] = 80
Array[-3] = 70
Array[-4] = 60
Array[-5] = 50
Array[-6] = 40
Array[-7] = 30
Array[-8] = 20
Array[-9] = 10


In [26]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [27]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [28]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [30]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
copied_err = arr[3:5].copy() # In this time I didn't slice it, I copied it
copied_err[:] = 0 # And I can change it without any effects to main array
copied_err

array([0, 0])

In [33]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
print(arr)
print(arr1)

[10 20 30  0  0 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


In [36]:
arr2d = np.array([[34,62,24], [56,73,74], [27,97,35]]) # Two dimentional array
arr2d

array([[34, 62, 24],
       [56, 73, 74],
       [27, 97, 35]])

In [37]:
arr2d.ndim

2

In [ ]:
#@title Expirament about dimensions in arrays
data_exp = [
    [
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35
            ]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ]
    ],
    [
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ]
    ],
    [
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ],
        [
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ],
            [
              [
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ],
        [
            [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],], [[
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ],
        [
            [34,62,24], [56,73,74], [27,97,35]
        ]
    ],]
        ]
    ],
            ]
        ]
    ]
]
arr_exp = np.array(data_exp)
print(f"Dimension: {arr_exp.ndim}")
print(arr_exp)

In [39]:
arr2d[1,1]

73

In [40]:
arr2d[1][1]

73

In [41]:
arr3d = np.array([
      [
        [34,62,24],
        [56,73,74],
        [27,97,35]
      ],
      [
        [34,62,24],
        [56,73,74],
        [27,97,35]
      ],
      [
        [34,62,24],
        [56,73,74],
        [27,97,35]
      ]
    ]) # Three dimentional array
arr3d

array([[[34, 62, 24],
        [56, 73, 74],
        [27, 97, 35]],

       [[34, 62, 24],
        [56, 73, 74],
        [27, 97, 35]],

       [[34, 62, 24],
        [56, 73, 74],
        [27, 97, 35]]])

In [42]:
arr3d[0]

array([[34, 62, 24],
       [56, 73, 74],
       [27, 97, 35]])

In [43]:
arr3d[0, 1]

array([56, 73, 74])

In [44]:
arr3d[0, 1, 2]

74

In [47]:
arr3d[0, 1, :3]

array([56, 73, 74])

In [48]:
arr3d[0][1][:3]

array([56, 73, 74])