# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
print("Numpy version:", np.version.version)
print("Numpy configurations:", np.show_config)

Numpy version: 1.25.2
Numpy configurations: <function show at 0x7858484d48b0>


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr = np.arange(0, 10) # 0dan 10gacha bo'lgan array (10 hisobga kirmaydi)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr2 = np.zeros((9))
print("Dimension:",arr2.ndim)
print("Array:", arr2)

Dimension: 1
Array: [0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Massiv yarating va uning xotira hajmini toping.




💡Ishora` size, itemsize

In [ ]:
print("Array:", arr)
print("Size:", arr.size, "elements")
print("Item size:", arr.itemsize, "bytes")

Array: [0 1 2 3 4 5 6 7 8 9]
Size: 10 elements
Item size: 8 bytes


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
tdv = np.zeros(12)
tdv[5] = 1
tdv

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr2 = np.arange(20, 59)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr_reversed = np.arange(0, 10)
arr_reversed = arr_reversed[::-1].copy()
arr_reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr3 = np.arange(12, 21).reshape(3, 3)
arr3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr4 = np.array([3, 7, 0, 0, 9, 0])
arr4.nonzero()

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr5 =  np.random.rand(2, 2, 2)
arr5

array([[[0.2104734 , 0.07834643],
        [0.59673174, 0.19842051]],

       [[0.64292644, 0.29422481],
        [0.0768024 , 0.66168598]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr6 = np.random.rand(9, 9)
print("Min:", arr6.min())
print("Max:", arr6.max())

Min: 0.017461658579976502
Max: 0.9919092449126219


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

**Natija:** *False*

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr_1 = np.random.rand(6, 3)
arr_2 = np.random.rand(3, 4)
arr_1.dot(arr_2)

array([[0.43165217, 0.69010106, 0.94512023, 0.93945149],
       [0.29923987, 0.25221894, 0.64674559, 0.52634186],
       [0.43687212, 0.37953719, 0.90785504, 0.74271719],
       [0.52507063, 0.73821311, 1.21265902, 1.14488079],
       [0.84372796, 0.91218285, 1.83854018, 1.6015934 ],
       [0.66158651, 0.58956249, 1.50174759, 1.24273236]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

**Natija** 9 va
10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])
print("a > b |" ,a > b)
print("a >= b |" ,a >= b)
print("a < b |" ,a < b)
print("a <= b |" ,a <= b)

a > b | [False False]
a >= b | [False False]
a < b | [ True  True]
a <= b | [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-24-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-24-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-24-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
a_1 = np.array([3, 4, 5, 6, 7, 8, 9])
a_2 = np.array([6, 2, 1, 4, 8 ,9, 10])
np.intersect1d(a_1, a_2)

array([4, 6, 8, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
random_numbers = np.random.randn(10)
meth1 = random_numbers[random_numbers > 0]
meth2 = random_numbers[np.floor(random_numbers) > 0]
meth3 = random_numbers[random_numbers.astype(int) > 0]
meth4 = random_numbers[np.trunc(random_numbers) > 0]

print("Original:", random_numbers)
print("%:", meth1)
print("np.floor:", meth2)
print("astype:", meth3)
print("np.trunc:", meth4)

Original: [-0.24008994  0.3465027   0.38101754 -0.56026352 -1.00990459  2.99664645
  0.92087801  0.50293732  0.67998079  1.21968993]
%: [0.3465027  0.38101754 2.99664645 0.92087801 0.50293732 0.67998079
 1.21968993]
np.floor: [2.99664645 1.21968993]
astype: [2.99664645 1.21968993]
np.trunc: [2.99664645 1.21968993]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr_b = np.tile(np.arange(3), 3).reshape(3, 3)
arr_b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
rand_arr = np.random.rand(10)
print("Sorted:",np.sort(rand_arr))
print("Unsorted:", rand_arr)

Sorted: [0.06249953 0.24926285 0.44099607 0.50803582 0.74030559 0.77536959
 0.79786306 0.95458481 0.97673628 0.98783546]
Unsorted: [0.24926285 0.44099607 0.97673628 0.50803582 0.74030559 0.79786306
 0.77536959 0.98783546 0.95458481 0.06249953]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a = np.random.rand(3)
b = np.random.rand(3)
print(np.array_equal(a, b))
print(np.allclose(a, b))

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
arr_c = np.random.rand(6, 3)
arr_d = np.random.rand(3, 4)
arr_c.dot(arr_d)

array([[1.02313739, 0.83166847, 0.62276808, 0.51546896],
       [1.26569107, 1.30152482, 1.07620122, 0.69313125],
       [0.84596052, 0.93215174, 0.87537569, 0.53648369],
       [1.05074748, 0.71592005, 0.64151701, 0.61140434],
       [1.18058129, 0.94085739, 0.81901173, 0.67623471],
       [1.12364854, 1.19202867, 1.05116475, 0.6611981 ]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
array_a = np.random.rand(5)
max = array_a.argmax()
array_a[max] = 0
array_a

array([0.66765488, 0.46961158, 0.5296091 , 0.18785844, 0.        ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D'),
tomorrow = today + np.timedelta64(1, 'D')

print("Kechagi sana:", yesterday)
print("Bugungi sana:", today)
print("Ertagangi sana:", tomorrow)

Kechagi sana: (numpy.datetime64('2024-02-14'),)
Bugungi sana: 2024-02-15
Ertagangi sana: 2024-02-16


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
np.arange('2016-01', '2016-02', dtype='datetime64[D]')

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
random_numbers = np.random.randn(10)
meth1 = random_numbers[random_numbers > 0]
meth2 = random_numbers[np.floor(random_numbers) > 0]
meth3 = random_numbers[random_numbers.astype(int) > 0]
meth4 = random_numbers[np.trunc(random_numbers) > 0]

print("Original:", random_numbers)
print("%:", meth1)
print("np.floor:", meth2)
print("astype:", meth3)
print("np.trunc:", meth4)

Original: [-0.34152041  0.14755925  0.37437803  0.6154269  -2.88461799 -0.07910044
  1.05039596  1.70881955 -0.24176168 -0.52416472]
%: [0.14755925 0.37437803 0.6154269  1.05039596 1.70881955]
np.floor: [1.05039596 1.70881955]
astype: [1.05039596 1.70881955]
np.trunc: [1.05039596 1.70881955]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 3, 4, 5, 6])
array3 = np.array([5, 5, 5, 5, 5])
np.add.reduce([array1, array2, array3])

array([ 8, 10, 12, 14, 16])

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
a_vector = np.array([1, 2, 3, 4, 5])
vwz = np.zeros(len(a_vector) + 3 * (len(a_vector) - 1))
vwz[::4] = a_vector
vwz

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
b = np.lib.stride_tricks.as_strided(a, shape=(11, 4), strides=(8,8))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
orig_array = np.array([5, 2, 8, 3, 5, 7, 8, 2, 3, 6, 7, 5, 8, 2])

# O'xshash qiymatlarni topish
counts = np.bincount(orig_array)
duplicates = np.where(counts > 1)[0] # nollarni olib tashlaymiz
duplicates

array([2, 3, 5, 7, 8])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`